### ISSUE TITLE
How to Use

### ISSUE THREAD

**Issue by vylryna** [yukikamome316/MineCode#6]
I'm a little confused on how to use this to generate codes, as there's no instructions.

How would I go about using this?

**Comment by zkr5471** [comment]
See source codes.

**Comment by yukikamome316** [comment]
> See source codes.

what the fuck

**Comment by yukikamome316** [comment]
> I'm a little confused on how to use this to generate codes, as there's no instructions.
> 
> 
> 
> How would I go about using this?

We're planning to make a reference of MineCode as soon as possible. So please attention to the modification of this repository. It must be something exciting for you.

**Comment by vylryna** [comment]
> 
> 
> > I'm a little confused on how to use this to generate codes, as there's no instructions.
> > How would I go about using this?
> 
> We're planning to make a reference of MineCode as soon as possible. So please attention to the modification of this repository. It must be something exciting for you.

Okay, thank you
